POST http://localhost:3005/api/auth/signin
Content-Type: application/json

{
  "email": "pxndxs.xd@pxndxs.com",
  "password": "pxndxs"
}

POST http://localhost:3005/api/auth/signup
Content-Type: application/json

{
  "email": "pxndxs.xd1@pxndxs.com",
  "name": "pxndxs",
  "paternalSurname": "pxndxs",
  "maternalSurname": "pxndxs",
  "password": "pxndxs"
}


GET http://localhost:3005/api/auth/revalidate-token
Authorization: Bearer <token>
