GET http://localhost:3005/api/program-details

GET http://localhost:3005/api/program-details/:id

GET http://localhost:3005/api/program-details/user/:userId

POST http://localhost:3005/api/program-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NTdiODc3LTU5NTctNDI1Mi04MzMyLWQ5ZGY4Zjk2MWY4MiIsImlhdCI6MTcwMTk5MzY3MywiZXhwIjoxNzAyMDgwMDczfQ.CuuH0dTKVV_D6jA2SwnTkWspOrNXPf9GYyGgmWrr-HA

{
  "userId": "5957b877-5957-4252-8332-d9df8f961f82",
  "nationality": "Bolivia",
  "genderId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1",
  "ciExtensionId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1",
  "birthDate": "2017-09-01"
}

PATCH http://localhost:3005/api/program-details/:id
Content-Type: application/json
Authorization: Bearer <token>

{
  "phone": "1234567890",
  "landline": "1234567890",
  "department": "La Paz",
  "address": "La Paz",
  "city": "La Paz"
}

DELETE http://localhost:3005/api/program-details/:id
Authorization: Bearer <token>
