GET http://localhost:3005/api/program-details

GET http://localhost:3005/api/program-details/:id

GET http://localhost:3005/api/program-details/user/:userId

POST http://localhost:3005/api/program-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0ZDg2YzE0LTkzNjctNGRhNC05OTk1LWVkOWUzYTQxN2ZjZiIsImlhdCI6MTcwNDExNzQ2MywiZXhwIjoxNzA0MjAzODYzfQ.3rHfOhU9ncKDnpjV_U2QfwFVtbPFQV0awI2MIE6AXWc

{
  "userId": "5957b877-5957-4252-8332-d9df8f961f82",
  "paymentMethodId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1",
  "registrationConditionId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1",
  "howToFindOutId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1"
}

PATCH http://localhost:3005/api/program-details/:id
Content-Type: application/json
Authorization: Bearer <token>

{
  "userId": "5957b877-5957-4252-8332-d9df8f961f82",
  "paymentMethodId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1",
  "registrationConditionId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1",
  "howToFindOutId": "664ef3f8-188d-4843-9a3f-c8282f2d1bb1"
}

DELETE http://localhost:3005/api/program-details/:id
Authorization: Bearer <token>
